"""add stakeholder_scenarios and chatroom scenario_id

Revision ID: e18bbd2376c7
Revises: 2153e68bd148
Create Date: 2026-04-03 16:31:00.270106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18bbd2376c7'
down_revision: Union[str, Sequence[str], None] = '2153e68bd148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stakeholder_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='场景名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='场景描述'),
    sa.Column('context_prompt', sa.Text(), nullable=False, comment='场景上下文 prompt'),
    sa.Column('suggested_persona_ids', sa.JSON(), nullable=True, comment='建议角色ID列表'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='利益相关者对话场景模板'
    )
    with op.batch_alter_table('stakeholder_chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_id', sa.Integer(), nullable=True, comment='关联场景模板ID'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholder_chat_rooms', schema=None) as batch_op:
        batch_op.drop_column('scenario_id')

    op.drop_table('stakeholder_scenarios')
    # ### end Alembic commands ###
