"""add emotion fields to stakeholder messages

Revision ID: 074e129df5d5
Revises: e18bbd2376c7
Create Date: 2026-04-03 17:17:25.368408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074e129df5d5'
down_revision: Union[str, Sequence[str], None] = 'e18bbd2376c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholder_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotion_score', sa.SmallInteger(), nullable=True, comment='情绪分数 -5~+5'))
        batch_op.add_column(sa.Column('emotion_label', sa.String(length=20), nullable=True, comment='情绪标签'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholder_messages', schema=None) as batch_op:
        batch_op.drop_column('emotion_label')
        batch_op.drop_column('emotion_score')

    # ### end Alembic commands ###
