"""add organization team persona_relationship tables

Revision ID: ce4fc17e244d
Revises: 81172b9df0ff
Create Date: 2026-04-08 11:39:15.659321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4fc17e244d'
down_revision: Union[str, Sequence[str], None] = '81172b9df0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='组织名称'),
    sa.Column('industry', sa.String(length=255), nullable=True, comment='行业'),
    sa.Column('description', sa.Text(), nullable=True, comment='组织描述'),
    sa.Column('context_prompt', sa.Text(), nullable=True, comment='注入角色 system prompt 的组织背景文本'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='组织/公司'
    )
    op.create_table('persona_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('organization_id', sa.Integer(), nullable=False, comment='所属组织ID'),
    sa.Column('from_persona_id', sa.String(length=50), nullable=False, comment='角色A的ID'),
    sa.Column('to_persona_id', sa.String(length=50), nullable=False, comment='角色B的ID'),
    sa.Column('relationship_type', sa.String(length=30), nullable=False, comment='关系类型: superior/subordinate/peer/cross_department'),
    sa.Column('description', sa.Text(), nullable=True, comment='关系描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'from_persona_id', 'to_persona_id', name='ux_persona_rel'),
    comment='角色间关系'
    )
    with op.batch_alter_table('persona_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persona_relationships_organization_id'), ['organization_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('organization_id', sa.Integer(), nullable=False, comment='所属组织ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='团队名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='团队职责描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='部门/团队'
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_organization_id'))

    op.drop_table('teams')
    with op.batch_alter_table('persona_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persona_relationships_organization_id'))

    op.drop_table('persona_relationships')
    op.drop_table('organizations')
    # ### end Alembic commands ###
