"""add competency evaluations

Revision ID: 11129e3565a6
Revises: ce4fc17e244d
Create Date: 2026-04-08 17:10:01.210602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11129e3565a6'
down_revision: Union[str, Sequence[str], None] = 'ce4fc17e244d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stakeholder_competency_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('report_id', sa.Integer(), nullable=False, comment='关联分析报告ID（一对一）'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='所属聊天室ID'),
    sa.Column('scores', sa.JSON(), nullable=False, comment='6维度评分JSON'),
    sa.Column('overall_score', sa.Float(), nullable=False, comment='总体平均分'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='评估时间'),
    sa.ForeignKeyConstraint(['report_id'], ['stakeholder_analysis_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['stakeholder_chat_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', name='uq_competency_eval_report_id'),
    comment='利益相关者能力评估（LLM-as-Judge 6维度）'
    )
    with op.batch_alter_table('stakeholder_competency_evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_competency_eval_room_id', ['room_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholder_competency_evaluations', schema=None) as batch_op:
        batch_op.drop_index('ix_competency_eval_room_id')

    op.drop_table('stakeholder_competency_evaluations')
    # ### end Alembic commands ###
