"""add coaching sessions and messages tables

Revision ID: 81172b9df0ff
Revises: ad572d1348de
Create Date: 2026-04-06 17:06:37.544169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81172b9df0ff'
down_revision: Union[str, Sequence[str], None] = 'ad572d1348de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stakeholder_coaching_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='所属聊天室ID'),
    sa.Column('report_id', sa.Integer(), nullable=False, comment='关联分析报告ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：active/completed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['report_id'], ['stakeholder_analysis_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['stakeholder_chat_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='利益相关者复盘对话会话'
    )
    with op.batch_alter_table('stakeholder_coaching_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_stakeholder_coaching_sessions_room_id', ['room_id'], unique=False)

    op.create_table('stakeholder_coaching_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：user/coach'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='消息时间'),
    sa.ForeignKeyConstraint(['session_id'], ['stakeholder_coaching_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='利益相关者复盘对话消息'
    )
    with op.batch_alter_table('stakeholder_coaching_messages', schema=None) as batch_op:
        batch_op.create_index('ix_stakeholder_coaching_messages_session_id', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholder_coaching_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_stakeholder_coaching_messages_session_id')

    op.drop_table('stakeholder_coaching_messages')
    with op.batch_alter_table('stakeholder_coaching_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_stakeholder_coaching_sessions_room_id')

    op.drop_table('stakeholder_coaching_sessions')
    # ### end Alembic commands ###
