"""add stakeholder chat_rooms and messages tables

Revision ID: 2153e68bd148
Revises: 
Create Date: 2026-04-03 10:01:55.656513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2153e68bd148'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='配置名称（唯一）'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='使用的模型'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='温度参数'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大 token 数'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='扩展元数据（JSON）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Agent 配置表，记录可复用的 Agent 配置'
    )
    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.create_index('ix_agent_configs_name', ['name'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='对话标题'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='默认使用的模型'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='对话状态：active/archived'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='扩展元数据（JSON）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.PrimaryKeyConstraint('id'),
    comment='对话表，记录 AI 对话会话'
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_conversations_status', ['status'], unique=False)

    op.create_table('file_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='归属用户ID（可为空；示例项目未强制外键约束）'),
    sa.Column('storage_type', sa.String(length=16), server_default=sa.text("'local'"), nullable=False, comment='存储类型：local/s3/oss'),
    sa.Column('bucket', sa.String(length=255), nullable=True, comment='存储桶/容器名称'),
    sa.Column('region', sa.String(length=64), nullable=True, comment='区域名（可为空）'),
    sa.Column('key', sa.String(length=512), nullable=False, comment='对象存储中的Key（路径）'),
    sa.Column('unique_key_hash', sa.String(length=64), nullable=False, comment='唯一键哈希：SHA-256(storage_type|bucket|key)'),
    sa.Column('size', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='文件大小（字节）'),
    sa.Column('etag', sa.String(length=64), nullable=True, comment='存储返回的ETag/校验值'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('original_filename', sa.String(length=255), nullable=True, comment='原始文件名'),
    sa.Column('kind', sa.String(length=50), nullable=True, comment='业务分类，如 avatar/document'),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('(false)'), nullable=False, comment='是否公共可读'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='扩展元数据（JSON）'),
    sa.Column('url', sa.String(length=1024), nullable=True, comment='公共/CDN URL快照（可选）'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='文件状态：pending/active/deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_key_hash'),
    comment='文件资源表，记录对象存储中的文件元数据'
    )
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.create_index('ix_file_assets_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_file_assets_owner_created', ['owner_id', 'created_at'], unique=False)

    op.create_table('stakeholder_chat_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='聊天室名称'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型：private/group'),
    sa.Column('persona_ids', sa.JSON(), nullable=False, comment='参与角色ID列表'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True, comment='最后消息时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='利益相关者聊天室'
    )
    with op.batch_alter_table('stakeholder_chat_rooms', schema=None) as batch_op:
        batch_op.create_index('ix_stakeholder_chat_rooms_last_message_at', ['last_message_at'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='所属对话ID'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'running'"), nullable=False, comment='Run 状态：running/completed/failed'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='使用的模型'),
    sa.Column('prompt_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='输入 token 数'),
    sa.Column('completion_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='输出 token 数'),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='总 token 数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Run 表，记录 LLM 调用追踪'
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('ix_runs_status', ['status'], unique=False)

    op.create_table('stakeholder_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='所属聊天室ID'),
    sa.Column('sender_type', sa.String(length=20), nullable=False, comment='发送者类型：user/persona/system'),
    sa.Column('sender_id', sa.String(length=100), nullable=False, comment='发送者ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='消息时间'),
    sa.ForeignKeyConstraint(['room_id'], ['stakeholder_chat_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='利益相关者聊天消息'
    )
    with op.batch_alter_table('stakeholder_messages', schema=None) as batch_op:
        batch_op.create_index('ix_stakeholder_messages_room_id', ['room_id'], unique=False)
        batch_op.create_index('ix_stakeholder_messages_room_timestamp', ['room_id', 'timestamp'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='所属对话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色：system/user/assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('run_id', sa.Integer(), nullable=True, comment='关联的 Run ID'),
    sa.Column('token_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Token 数量'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='扩展元数据（JSON）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='消息表，记录对话中的消息'
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conversation_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index('ix_messages_conversation_id', ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_conversation_id')
        batch_op.drop_index('ix_messages_conversation_created')

    op.drop_table('messages')
    with op.batch_alter_table('stakeholder_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_stakeholder_messages_room_timestamp')
        batch_op.drop_index('ix_stakeholder_messages_room_id')

    op.drop_table('stakeholder_messages')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_status')
        batch_op.drop_index('ix_runs_conversation_id')

    op.drop_table('runs')
    with op.batch_alter_table('stakeholder_chat_rooms', schema=None) as batch_op:
        batch_op.drop_index('ix_stakeholder_chat_rooms_last_message_at')

    op.drop_table('stakeholder_chat_rooms')
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_file_assets_owner_created')
        batch_op.drop_index('ix_file_assets_created_at')

    op.drop_table('file_assets')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_status')
        batch_op.drop_index('ix_conversations_created_at')

    op.drop_table('conversations')
    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_configs_name')

    op.drop_table('agent_configs')
    # ### end Alembic commands ###
