"""add defense_sessions table

Revision ID: 5f310be132ee
Revises: c81263f68d3d
Create Date: 2026-04-14 18:17:46.610517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f310be132ee'
down_revision: Union[str, Sequence[str], None] = 'c81263f68d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defense_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('persona_id', sa.String(length=100), nullable=False, comment='关联 Persona ID'),
    sa.Column('scenario_type', sa.String(length=50), nullable=False, comment='场景类型'),
    sa.Column('document_summary', sa.JSON(), nullable=False, comment='文档摘要 (结构化)'),
    sa.Column('question_strategy', sa.JSON(), nullable=True, comment='提问策略 (LLM 生成)'),
    sa.Column('room_id', sa.Integer(), nullable=True, comment='关联聊天室 ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: preparing/in_progress/completed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='答辩准备会话'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defense_sessions')
    # ### end Alembic commands ###
